CREATE TABLE Customer_T
(CustomerID numeric(11,0)  NoT NULL,
CustomerName VARCHAR(25) NOT NULL,
CustomerAddress VARCHAR(30),
CustomerCity VARCHAR(20),
CustomerState CHAR(2),
CustomerPostalCode VARCHAR(9),
CONSTRAINT Customer_PK PRIMARY KEY (CustomerID))


select * from Order_T



CREATE TABLE Order_T
(OrderID numeric(11,0) NOT NULL,
OrderDate DATE DEFAULT GETDATE(),
CustomerID numeric(11,0),
CONSTRAINT Order_PK PRIMARY KEY (OrderID),
CONSTRAINT Order_FK FOREIGN KEY (CustomerID) REFERENCES Customer_T(CustomerID));





CREATE TABLE Product_T
(ProductID numeric(11,0) NOT NULL,
ProductDescription VARCHAR(50),
ProductFinish VARCHAR(20),
ProductStandardPrice DECIMAL(6,2),
CONSTRAINT Product_PK PRIMARY KEY (ProductID));





INSERT INTO CUSTOMER_T(CUSTOMERID,CUSTOMERNAME,CUSTOMERADDRESS, CUSTOMERCITY, CUSTOMERSTATE, CUSTOMERPOSTALCODE) VALUES (01,'PAVANKUMAR MULGUND','123 CLARENCE','BUFFALO','NY','14281');
INSERT INTO CUSTOMER_T(CUSTOMERID,CUSTOMERNAME,CUSTOMERADDRESS, CUSTOMERCITY, CUSTOMERSTATE, CUSTOMERPOSTALCODE) VALUES (02,'RAJ SHARMAN','212 WILLIAMSVILE','BUFFALO','NY', '14211');
INSERT INTO CUSTOMER_T(CUSTOMERID,CUSTOMERNAME,CUSTOMERADDRESS, CUSTOMERCITY, CUSTOMERSTATE, CUSTOMERPOSTALCODE) VALUES (03,'MANISH GUPTA','881 WILLIAMSVILE','BUFFALO','NY', '14221');
INSERT INTO CUSTOMER_T(CUSTOMERID,CUSTOMERNAME,CUSTOMERADDRESS, CUSTOMERCITY, CUSTOMERSTATE, CUSTOMERPOSTALCODE) VALUES (04,'RAGHAV RAO','1234 AMHERST','AMHERST','NY', '14226');
INSERT INTO CUSTOMER_T(CUSTOMERID,CUSTOMERNAME,CUSTOMERADDRESS, CUSTOMERCITY, CUSTOMERSTATE, CUSTOMERPOSTALCODE) VALUES (05,'PAVANKUMAR MULGUND','123 Englewood Avenue','BUFFALO','NY','14281');






INSERT INTO ORDER_T(ORDERID, ORDERDATE, CUSTOMERID) VALUES (001, '15-OCT-2015', 02);
INSERT INTO ORDER_T(ORDERID, ORDERDATE, CUSTOMERID) VALUES (002, '15-OCT-2015', 04);
INSERT INTO ORDER_T(ORDERID, ORDERDATE, CUSTOMERID) VALUES (003, '15-OCT-2015', 03);
INSERT INTO ORDER_T(ORDERID, ORDERDATE, CUSTOMERID) VALUES (004, '15-OCT-2015', 01);
INSERT INTO ORDER_T(ORDERID, ORDERDATE, CUSTOMERID) VALUES (005, '15-OCT-2015', 05);





UPDATE CUSTOMER_T SET CUSTOMERPOSTALCODE='14211' WHERE CUSTOMERPOSTALCODE='14221';
UPDATE CUSTOMER_T SET CUSTOMERPOSTALCODE='14211';
UPDATE CUSTOMER_T SET CUSTOMERPOSTALCODE='14211' WHERE CUSTOMERNAME='RAGHAV RAO';
UPDATE CUSTOMER_T SET CUSTOMERPOSTALCODE='14211' WHERE CUSTOMERNAME='RAJ SHARMAN';

UPDATE ORDER_T SET ORDERDATE  = '17-OCT-2015' WHERE  ORDER_T.CUSTOMERid=01;
UPDATE ORDER_T SET ORDERDATE  = '17-OCT-2015' WHERE ORDER_T.CUSTOMERid=05;


select * from Customer_T




create table Physician
(
physicianid int identity,
specialty varchar(20)
)