// <auto-generated />
namespace TwitterTrial.DBContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ShuffleForeignKeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShuffleForeignKeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201603270427352_ShuffleForeignKeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
