//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationSecurityScorecard.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InfoSecSurveyEntities : DbContext
    {
        public InfoSecSurveyEntities()
            : base("name=InfoSecSurveyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnswerInstance> AnswerInstances { get; set; }
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Communication_Log> Communication_Log { get; set; }
        public virtual DbSet<Communication_Type> Communication_Type { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Questionnaire> Questionnaires { get; set; }
        public virtual DbSet<Questionnaire_Instance> Questionnaire_Instance { get; set; }
        public virtual DbSet<Questionnaire_Section> Questionnaire_Section { get; set; }
        public virtual DbSet<Survey> Surveys { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
