//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationSecurityScorecard.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Survey()
        {
            this.Questionnaire_Instance = new HashSet<Questionnaire_Instance>();
        }
    
        public int SurveyId { get; set; }
        public Nullable<System.DateTime> Survey_StartDate { get; set; }
        public Nullable<System.DateTime> Survey_EndDate { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
        public string Date_Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string Date_Created_By { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Questionnaire_Instance> Questionnaire_Instance { get; set; }
        public virtual User User { get; set; }
    }
}
